
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="text-center py-6 mt-12 bg-white border-t border-slate-200">
      <p className="text-slate-500">
        Generated by a world-class senior frontend React engineer with Gemini.
      </p>
    </footer>
  );
};

export default Footer;
